baseline_model: fno3d
best_value: 0.00034304604219820197
params:
  lr: 0.0017288069352721916
  weight_decay: 8.931675097346611e-06
  optimizer: adamw
  use_lookahead: true
  gradient_clip: 5.0
  batch_size: 1
  scheduler_power: 2
  warmup_steps: 0
  min_lr_ratio: 0.16742683806983305
  modes1: 10
  modes2: 6
  modes3: 4
  width: 32
  n_layers: 4
suggested_config_patch:
  model:
    Baseline:
      model_name: fno3d
  train:
    Baseline:
      lr: 0.0017288069352721916
      weight_decay: 8.931675097346611e-06
      optimizer: adamw
      use_lookahead: true
      gradient_clip: 5.0
      scheduler:
        power: 2
        warmup_steps: 0
        warmup_type: linear
        min_lr: 0.00028944867880582154
        min_lr_warmup: 2.8944867880582155e-05
  data:
    Baseline:
      train_batch_size: 1
