baseline_model: unet
best_value: 3.0665694636267586
params:
  lr: 9.745399020374078e-05
  weight_decay: 6.672367170464208e-05
  optimizer: adamw
  use_lookahead: false
  gradient_clip: 1.0
  batch_size: 2
  scheduler_power: 1
  warmup_steps: 14
  min_lr_ratio: 0.22567472193240465
  base_channels: 64
  use_residual: false
suggested_config_patch:
  model:
    Baseline:
      model_name: unet
  train:
    Baseline:
      lr: 9.745399020374078e-05
      weight_decay: 6.672367170464208e-05
      optimizer: adamw
      use_lookahead: false
      gradient_clip: 1.0
      scheduler:
        power: 1
        warmup_steps: 14
        warmup_type: linear
        min_lr: 2.199290214043249e-05
        min_lr_warmup: 2.199290214043249e-06
  data:
    Baseline:
      train_batch_size: 2
