baseline_model: unet
best_value: 0.0009712135661519259
params:
  lr: 0.003491096030337895
  weight_decay: 0.0005724341889174792
  optimizer: adamw
  use_lookahead: false
  gradient_clip: 5.0
  batch_size: 4
  scheduler_power: 3
  warmup_steps: 8
  min_lr_ratio: 0.0464815219112705
  base_channels: 64
  use_residual: true
suggested_config_patch:
  model:
    Baseline:
      model_name: unet
  train:
    Baseline:
      lr: 0.003491096030337895
      weight_decay: 0.0005724341889174792
      optimizer: adamw
      use_lookahead: false
      gradient_clip: 5.0
      scheduler:
        power: 3
        warmup_steps: 8
        warmup_type: linear
        min_lr: 0.00016227145662850033
        min_lr_warmup: 1.6227145662850033e-05
  data:
    Baseline:
      train_batch_size: 4
