model:
  CAE:
    conv_config:
      output_channels: 128
      hidden_channels:
      - 64
      dim: 2
      paddings: 0
      strides: 2
      normalization: null
      activation: elu
training:
  CAE:
    lr: 0.00828214765761879
    weight_decay: 0.0011363161966523366
    optimizer: adamw
    use_lookahead: false
    gradient_clip: -1.0
    train_batch_size: 16
    scheduler:
      power: 2
      warmup_steps: 13
      warmup_type: linear
      min_lr: 0.0026702302964439926
      min_lr_warmup: 0.00026702302964439926
