model:
  CAEst:
    spatial_conv_config:
      output_channels: 32
      hidden_channels: &id001 []
      dim: 2
      paddings: 0
      strides: 2
      normalization: null
      activation: silu
    temporal_conv_config:
      output_channels: 32
      hidden_channels: *id001
      dim: 2
      paddings: 0
      strides: 2
      normalization: null
      activation: silu
    spatial_tconv_config:
      input_channels: 32
      output_channels: <set_input_channels>
      hidden_channels: []
      dim: 2
      paddings: 0
      output_paddings:
      - !!python/tuple
        - 1
        - 1
      strides: 2
      normalization: null
      activation: silu
    temporal_tconv_config:
      input_channels: 32
      output_channels: 1
      hidden_channels: []
      dim: 2
      paddings: 0
      output_paddings:
      - !!python/tuple
        - 1
        - 0
      strides: 2
      normalization: null
      activation: silu
    no_flatten_dim: <compute_from_sample>
training:
  CAE:
    lr: 0.009575930699581986
    weight_decay: 0.0002824496575669884
    optimizer: adamw
    use_lookahead: false
    gradient_clip: -1.0
    train_batch_size: 16
    scheduler:
      power: 1
      warmup_steps: 6
      warmup_type: linear
      min_lr: 0.0023350388794555303
      min_lr_warmup: 0.00023350388794555305
