CAE:
   data_path: /globalsc/ulb/atm/baffetti/research/Transformer/ArtFire_files/data/D_t2001_f13_z256_x64.npy
   split: [0.6,0.2,0.2]
   normalize: true
   train_batch_size: 16
   val_batch_size: 64
   test_batch_size: 64
   loader:
     loaders_num_workers: 4
     pin_memory: false
     persistent_workers: false

Transformer:
  split: [0.6,0.2,0.2]
  horizon: 30
  normalize: true
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size: 64
  cae_dataloader:
    batch_size: 64
    loaders_num_workers: 4
    pin_memory: true
    persistent_workers: true
  loader:
    loaders_num_workers: 4
    pin_memory: true
    persistent_workers: true

ArtFire:
  split: [0.6,0.2,0.2]
  normalize: true
  train_batch_size: 32
  val_batch_size: 32
  test_batch_size:  64
  loader:
    loaders_num_workers: 4
    pin_memory: true
    persistent_workers: true

Baseline:
  data_path: /globalsc/ulb/atm/baffetti/research/Transformer/ArtFire_files/data/D_t2001_f13_z256_x64.npy
  split: [0.6,0.2,0.2]
  horizon: 30
  normalize: true
  train_batch_size: 16
  val_batch_size: 16
  test_batch_size: 32
  loader:
    loaders_num_workers: 4
    pin_memory: true
    persistent_workers: true
