CAE:
  spatial_conv_config:
    input_channels: 13
    output_channels: 64
    hidden_channels: [32]
    dim: 2
    paddings: 0
    strides: 2
  temporal_conv_config:
    input_channels: 1
    output_channels: 64
    hidden_channels: [32]
    dim: 2
    paddings: 0
    strides: 2

  spatial_tconv_config:
    input_channels: 64
    output_channels: 13
    hidden_channels: [32]
    dim: 2
    paddings: 0
    output_paddings: [ [0, 0], [1, 1] ]
    strides: 2
  temporal_tconv_config:
    input_channels: 64
    output_channels: 1
    hidden_channels: [32]
    dim: 2
    paddings: 0
    output_paddings: [[0, 0], [1, 0]]
    strides: 2
  no_flatten_dim: [64,15,3]

Transformer:
  n_tokens: 63
  token_dim: 2880
  d_model: 512
  n_heads: 8
  n_layers: 4
  dropout: 0.1
  use_residual: true
  mlp_config:
    hidden_layers: [512, 256]
    dropout_p: 0.0
    normalization: None
    activation: gelu
    initialization: default
