CAEst:
  spatial_conv_config:
    input_channels: 13
    output_channels: 64
    hidden_channels: [32]
    dim: 2
    paddings: 0
    strides: 2
  temporal_conv_config:
    input_channels: 1
    output_channels: 64
    hidden_channels: [32]
    dim: 2
    paddings: 0
    strides: 2

  spatial_tconv_config:
    input_channels: 64
    output_channels: 13
    hidden_channels: [32]
    dim: 2
    paddings: 0
    output_paddings: [ [0, 0], [1, 1] ]
    strides: 2
  temporal_tconv_config:
    input_channels: 64
    output_channels: 1
    hidden_channels: [32]
    dim: 2
    paddings: 0
    output_paddings: [[0, 0], [1, 0]]
    strides: 2
  no_flatten_dim: [64,15,3]

Transformer:
  n_tokens: 63
  token_dim: 2880
  d_model: 512
  n_heads: 8
  n_layers: 4
  dropout: 0.1
  use_residual: true
  mlp_config:
    hidden_layers: [512, 256]
    dropout_p: 0.0
    normalization: None
    activation: gelu
    initialization: default


CAE:
  conv_config:
    output_channels: 128
    hidden_channels: [64]
    dim: 2
    paddings: 0
    strides: 2
    normalization: None
    activation: silu

Baseline:
  model_name: fno2d
  UNet:
    out_channels: null
    base_channels: 32
    use_residual: true
  ResNet:
    out_channels: null
    hidden_channels: 64
    n_blocks: 6
    use_residual: true
  FNO2D:
    out_channels: null
    modes1: 12
    modes2: 12
    width: 32
    n_layers: 4
    use_residual: true
  FNO3D:
    out_channels: null
    modes1: 8
    modes2: 8
    modes3: 8
    width: 20
    n_layers: 4
