CAE:
  device: cuda
  lr: 0.005180583798538568
  weight_decay: 0.0007482351349895603
  optimizer: adamw
  use_lookahead: false
  n_epochs: 60
  gradient_clip: -1
  saving_folder: training_CAE
  scheduler:
    power: 1
    min_lr: 0.0022932130341988483
    min_lr_warmup: 0.00022932130341988483
    warmup_steps: 2
    warmup_type: linear

Transformer:
  device: cuda
  lr: 1.0e-4
  weight_decay: 1.0e-4
  optimizer: adamw
  use_lookahead: true
  n_epochs:  60
  gradient_clip: 3
  saving_folder: training_Transformer
  scheduler:
    power: 2
    min_lr: 5.0e-5
    min_lr_warmup: 5.0e-6
    warmup_steps: 15
    warmup_type: linear
  criterion:
    type: MSE
    lambda_t1: 0.5
    lambda_t2: 0.5

ArtFire:
  device: cuda
  lr: 1.0e-6
  weight_decay: 1.0e-3
  optimizer: adamw
  use_lookahead: true
  n_epochs: 40
  gradient_clip: 1
  saving_folder: training_ArtFire
  scheduler:
    power: 2
    min_lr: 5.0e-8
    min_lr_warmup: 5.0e-8
    warmup_steps: 15
    warmup_type: linear
  criterion:
    type: MSE
    lambda_t1: 0.5
    lambda_t2: 0.5

Baseline:
  device: cuda
  lr: 1.0e-4
  weight_decay: 1.0e-4
  optimizer: adamw
  use_lookahead: false
  n_epochs: 60
  gradient_clip: 1
  saving_folder: training_Baseline
  scheduler:
    power: 2
    min_lr: 5.0e-5
    min_lr_warmup: 5.0e-6
    warmup_steps: 10
    warmup_type: linear
